version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: newstrust-postgres
    environment:
      POSTGRES_DB: newstrust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - newstrust-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: newstrust-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: newstrust
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      BCRYPT_ROUNDS: 12
      RATE_LIMIT_WINDOW: 900000
      RATE_LIMIT_MAX: 100
      CORS_ORIGIN: http://localhost:3000
      LOG_LEVEL: info
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - newstrust-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: newstrust-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_APP_NAME: NewsTrust
      NEXT_PUBLIC_APP_VERSION: 1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - newstrust-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: newstrust-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - newstrust-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  newstrust-network:
    driver: bridge
